### PR TITLE
Mute Bug fixed

### LINKED ISSUE #445: Mute sometimes stops working
Sometimes mute feature stops working. It is not known whether this is a bug of the Spotify feature or the mute system.

### PR DESCRIPTION
**Pull request by buddy200**
The mute bug is fixed and spotify now plays song or playlists after the output is finished
closes #445 

Pull request status:
- [x] Tests added/updated
- [x] 80 % Coverage
- [x] Code conventions
- [x] Doku required and added
- [x] Ready for review

### CODE REVIEW

**Comment by Bensge** [comment]
Resume doesn't work on my machine anymore

File: plugins/spotify/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/spotify/logic/PlayerLogic.java [hunk 1]
```diff
@@ -224,6 +256,10 @@ public boolean pause() {
 	 * @return a boolean. true if the command was executed, else if the command failed
 	 */
 	public boolean skip() {
+		if (this.suppressed) {
```
Comment (Bensge) [inline plugins/spotify/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/spotify/logic/PlayerLogic.java]: this essentially breaks skip and back, right?

File: plugins/spotify/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/spotify/logic/PlayerLogic.java [hunk 2]
```diff
@@ -321,13 +361,21 @@ void setSuppressed(boolean suppressed) {
...
 				}
 				this.suppressed = false;
-			} else if (suppressed && isPlaying) {
+			} else if (suppressed) {
+				if(isPlaying) {
+					pause();
+				}
 				// Consider pausing playback
-				pause();
 				this.suppressed = true;
```
Comment (Bensge) [inline plugins/spotify/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/spotify/logic/PlayerLogic.java]: this is potentially dangerous. When I initially designed the suppression-System, I assumed that `suppressed` is only ever true when playback was actually interrupted.

File: plugins/spotify/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/spotify/logic/PlayerLogic.java [hunk 3]
```diff
@@ -201,6 +230,10 @@ public ArtistEntity playArtist(int artistNumber) {
 	 * @return a boolean. true if the command was executed, else if the command failed
 	 */
 	public boolean resume() {
+		if (this.suppressed) {
+			this.postSuppressionAction = PostSuppressionAction.NONE;
```
Comment (Bensge) [inline plugins/spotify/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/spotify/logic/PlayerLogic.java]: this breaks resume
