### PR TITLE
Changes TTS so the output is not closed every time.

### LINKED ISSUE #158: Speech not working on Linux
The speech recognition does not work on linux. The wake up command is regocnized but every command after that is not processed.
Tested and replicated on two Ubuntu operating systems (16.04 and 16.10).

### PR DESCRIPTION
**Pull request by neumantm**
Changes the TextToSpeech class to use a single SourceDataLine instead of many Clips.
Therefor the Line does not need to be closed after each speech output, which messes with PulseAudio, which is the audio manager under most linux distributions.

Fixes #158 
Minor change.

Pull request status:
- No Tests added/updated, because TTS works with AudioLines, which are not mockable.
- [ ] Doku required and added
- [x] Ready for review

### CODE REVIEW

File: core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/speech/tts/TextToSpeech.java [hunk 1]
```diff
@@ -40,74 +40,133 @@
...
-		} catch (MaryConfigurationException e) {
+
+			Voice voice = Voice.getVoice("dfki-poppy-hsmm");
+			this.mary.setVoice(voice.getName());
+
+			// We need to do this, because the audio format depends on the voice of mary
+			AudioFormat audioFormat = voice.dbAudioFormat();
+
+			if (!AudioSystem.isLineSupported(new DataLine.Info(SourceDataLine.class, audioFormat))) {
+				this.logger.error("The Audio System does not support the required ");
```
Comment (Legion2) [inline core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/speech/tts/TextToSpeech.java]: throw a exception

File: core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/speech/recognizer/manager/AbstractSpeechRecognizerManager.java [hunk 2]
```diff
@@ -191,11 +187,6 @@ public void handleListeningState(boolean listening) {
 		 */
 	}
 
-	/**
-	 * Notify the System that sound is (not longer) Playing
-	 * T O D O private void notify(boolean listening) {}
```
Comment (MakinZeel) [inline core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/speech/recognizer/manager/AbstractSpeechRecognizerManager.java]: TODO for the Notify method for the Message-Bus
Maybe do not delete yet

`Notify the System that sound is (not longer) Playing` ->
`Notify the System that SR is (not longer) Listening`

Comment (neumantm) [reply core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/speech/recognizer/manager/AbstractSpeechRecognizerManager.java]: Opened Issue #203 for that.

**Comment by neumantm** [comment]
After the changes by @Legion2 Amy hears herself again in my setup.
I will commit some changes to fix this shortly.

**Comment by neumantm** [comment]
@MakinZeel It still works under linux.

File: core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/speech/recognizer/manager/AbstractSpeechRecognizerManager.java [hunk 3]
```diff
@@ -191,11 +187,6 @@ public void handleListeningState(boolean listening) {
 		 */
```
Comment (MakinZeel) [inline core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/speech/recognizer/manager/AbstractSpeechRecognizerManager.java]: Because you created new Issue, you can delete this comment
