### PR TITLE
Audio manager

### LINKED ISSUE #245: LineUnavailableException in Dockercontainer

### PR DESCRIPTION
**Pull request by neumantm**
This will add the central audio manager to the core
Needed to fix #245.

This part is not tested for now, because this code interacts with low level system utilities and runs highly parallel.

Pull request status:
- [x] Code conventions
- [x] Doku required and added: [Wiki](https://github.com/AmyAssist/Amy/wiki/AudioSystem)
- [x] Ready for review

### CODE REVIEW

File: core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/audio/InternalAudioManagerService.java [hunk 1]
```diff
@@ -0,0 +1,224 @@
...
+	@Override
+	public void registerAudioEnvironment(AudioEnvironment environment) {
+		UUID aei = environment.getAudioEnvironmentIdentifier();
+
+		if (this.registry.containsKey(aei))
+			throw new IllegalStateException("An audio environment with the same identifier is already registered!");
+		this.registry.put(aei, environment);
+
+		if (this.running) {
+			environment.start();
```
Comment (Legion2) [inline core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/audio/InternalAudioManagerService.java]: start the environment before putting it in the regisry

File: core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/audio/InternalAudioManagerService.java [hunk 2]
```diff
@@ -0,0 +1,224 @@
...
+			throw new IllegalStateException("Property " + PROPERTY_LOCAL_AUDIO + " missing in audio manager config.");
+	}
+
+	@Override
+	public void registerAudioEnvironment(AudioEnvironment environment) {
+		UUID aei = environment.getAudioEnvironmentIdentifier();
+
+		if (this.registry.containsKey(aei))
+			throw new IllegalStateException("An audio environment with the same identifier is already registered!");
+		this.registry.put(aei, environment);
```
Comment (Legion2) [inline core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/audio/InternalAudioManagerService.java]: synchronize with the registry for atomic operation

File: core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/audio/InternalAudioManagerService.java [hunk 3]
```diff
@@ -0,0 +1,224 @@
...
+	 * registered.
+	 * 
+	 * @param identifier
+	 *            The identifier of the environment
+	 * @return The environment
+	 */
+	private AudioEnvironment safelyGetEnv(UUID identifier) {
+		if (!this.registry.containsKey(identifier))
+			throw new IllegalArgumentException("This audio environment is not registered in this audio manager.");
+		return this.registry.get(identifier);
```
Comment (Legion2) [inline core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/audio/InternalAudioManagerService.java]: synchronize with the registry for atomic operation

File: core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/audio/InternalAudioManagerService.java [hunk 4]
```diff
@@ -0,0 +1,224 @@
...
+
+	private Map<UUID, AudioEnvironment> registry;
+
+	private boolean running = false;
+
+	@PostConstruct
+	private void init() {
+		loadAndCheckProperties();
+
+		this.registry = new HashMap<>();
```
Comment (Legion2) [inline core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/audio/InternalAudioManagerService.java]: use a concurrentHashMap

File: core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/audio/InternalAudioManagerService.java [hunk 5]
```diff
@@ -0,0 +1,224 @@
...
+			throw new IllegalStateException("An audio environment with the same identifier is already registered!");
+		this.registry.put(aei, environment);
+
+		if (this.running) {
+			environment.start();
+		}
+	}
+
+	@Override
+	public void unregisterAudioEnvironment(UUID identifier) {
```
Comment (Legion2) [inline core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/audio/InternalAudioManagerService.java]: not thread safe

File: core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/audio/environment/AudioEnvironment.java [hunk 6]
```diff
@@ -0,0 +1,339 @@
...
+	 * @param audioToPlay
+	 *            The audio output to play. This must have the format returned by {@link #getOutputFormat()}.
+	 * @param behavior
+	 *            How to behave if there is an output already
+	 * @throws IllegalArgumentException
+	 *             When the audioToPlay has the wrong format.
+	 * @throws IllegalStateException
+	 *             When the behavior is unknown
+	 */
+	public void playAudio(AudioOutput audioToPlay, AudioManager.OutputBehavior behavior) {
```
Comment (Legion2) [inline core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/audio/environment/AudioEnvironment.java]: use lock to synchronize different input threads trying to modify the queue

File: core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/audio/InternalAudioManagerService.java [hunk 7]
```diff
@@ -97,22 +97,24 @@ private void loadAndCheckProperties() {
 	public void registerAudioEnvironment(AudioEnvironment environment) {
 		UUID aei = environment.getAudioEnvironmentIdentifier();
 
-		if (this.registry.containsKey(aei))
-			throw new IllegalStateException("An audio environment with the same identifier is already registered!");
-		this.registry.put(aei, environment);
-
 		if (this.running) {
 			environment.start();
```
Comment (Legion2) [inline core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/audio/InternalAudioManagerService.java]: start the environment only if is is put in the registry

File: core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/audio/InternalAudioManagerService.java [hunk 8]
```diff
@@ -0,0 +1,234 @@
...
+		if (this.config.getProperty(PROPERTY_LOCAL_AUDIO) == null)
+			throw new IllegalStateException("Property " + PROPERTY_LOCAL_AUDIO + " missing in audio manager config.");
+	}
+
+	@Override
+	public void registerAudioEnvironment(AudioEnvironment environment) {
+		UUID aei = environment.getAudioEnvironmentIdentifier();
+
+		if (this.running) {
+			environment.start();
```
Comment (Legion2) [inline core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/audio/InternalAudioManagerService.java]: start the environment only if is is put in the registry

File: api/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/audio/AudioManager.java [hunk 9]
```diff
@@ -0,0 +1,128 @@
...
+
+	/**
+	 * Interrupts the audio output on the audio environment specified by the given identifier.
+	 * 
+	 * If the environment is currently outputting a global audio, this will interrupt the output on all environments.
+	 * 
+	 * @param identifier
+	 *            The identifier of the audio environment to interrupt.
+	 */
+	void interruptAudio(UUID identifier);
```
Comment (Legion2) [inline api/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/audio/AudioManager.java]: interrupt? do this stop the audio? what is with the queued audio?

File: core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/audio/AudioOutput.java [hunk 10]
```diff
@@ -0,0 +1,82 @@
...
+	 * @return The {@link AudioFormat} of this AudioOutput
+	 */
+	public AudioFormat getFormat() {
+		return this.ais.getFormat();
+	}
+
+	/**
+	 * Tries to close the input stream
+	 */
+	public void tryToCloseStream() {
```
Comment (Legion2) [inline core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/audio/AudioOutput.java]: how can the caller verify that the stream is closed or not

File: core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/audio/QueuedInputStream.java [hunk 11]
```diff
@@ -0,0 +1,118 @@
...
+ */
+public class QueuedInputStream extends InputStream {
+
+	private static final int QUEUE_SIZE = 10000;
+
+	/**
+	 * The queue of this input stream. Every normal value v should follow this rule: 0<=v<255 A -1 signals the end of
+	 * this stream. Other values are not allowed.
+	 */
+	private BlockingQueue<Integer> queue;
```
Comment (Legion2) [inline core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/audio/QueuedInputStream.java]: this is a big overhead, each moved integer 0 - 255 creates a object

File: core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/audio/environment/AudioEnvironment.java [hunk 12]
```diff
@@ -0,0 +1,256 @@
...
+	 * 
+	 * This stream needs to be read from fast enough. Otherwise this stream will end.
+	 * 
+	 * When this stream is no longer needed, it should be closed.
+	 * 
+	 * @return The stream.
+	 */
+	public AudioInputStream getAudioInputStream() {
+		QueuedInputStream qis = new QueuedInputStream();
+		this.inputStreams.add(qis);
```
Comment (Legion2) [inline core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/audio/environment/AudioEnvironment.java]: how are inputStreams removed form this list when they are closed?

File: core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/audio/QueuedInputStream.java (hunk 11 above)
Comment (neumantm) [reply core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/audio/QueuedInputStream.java]: Thats who Java works. Wrapper Objects are not that bad. What would you propose as an alternative?

File: core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/audio/environment/AudioEnvironment.java (hunk 12 above)
Comment (neumantm) [reply core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/audio/environment/AudioEnvironment.java]: The input worker does that.

File: core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/audio/environment/AbstractAudioEnvironment.java [hunk 13]
```diff
@@ -0,0 +1,234 @@
...
+		this.inputThread.start();
+	}
+
+	/**
+	 * @see de.unistuttgart.iaas.amyassist.amy.core.audio.environment.AudioEnvironment#stop()
+	 */
+	@Override
+	public void stop() {
+		this.outputThread.interrupt();
+		this.inputThread.interrupt();
```
Comment (Legion2) [inline core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/audio/environment/AbstractAudioEnvironment.java]: this does not work

File: api/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/audio/sound/SoundFactory.java [hunk 14]
```diff
@@ -0,0 +1,76 @@
...
+
+	/**
+	 * Creates a new sound from the file at the given URL.
+	 * 
+	 * @param location
+	 *            The URL of the file to load
+	 * @return The loaded {@link Sound} object.
+	 * @throws UnsupportedAudioFileException
+	 *             When the file at the URL is not in a supported format
+	 * @throws IOException
```
[the remark this answers is not in the document]
Comment (neumantm) [reply api/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/audio/sound/SoundFactory.java]: Like stated: `When the file at the URL is not in a supported format`

File: core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/audio/environment/AbstractAudioEnvironment.java (hunk 13 above)
Comment (neumantm) [reply core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/audio/environment/AbstractAudioEnvironment.java]: It does for me. Can you try again after the latest commit?

File: core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/speech/LocalAudioUserInteraction.java [hunk 15]
```diff
@@ -86,31 +87,15 @@ public void stop() {
...
-		TargetDataLine mic = null;
 		try {
-			mic = AudioSystem.getTargetDataLine(this.getFormat());
-			mic.open(this.getFormat());
-			mic.start();
-			return new AudioInputStream(mic);
-		} catch (LineUnavailableException e) {
-			throw new RuntimeExceptionRecognizerCantBeCreated("AudioInputStream can't be created", e);
+			return this.am
+					.getInputStreamOfAudioEnvironment(this.am.getAllRegisteredAudioEnvironments().iterator().next());
```
Comment (Legion2) [inline core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/speech/LocalAudioUserInteraction.java]: get the local AudioEnvironment not a random one

File: core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/speech/data/Sounds.java [hunk 16]
```diff
@@ -38,16 +44,17 @@
 	 */
 	SINGLE_CALL_STOP_BEEP("single_call_stop_beep.wav");
 
-	private String fileName = "de/unistuttgart/iaas/amyassist/amy/core/speech/data/sounds/";
+	private static final String DIRECTORY = "de/unistuttgart/iaas/amyassist/amy/core/speech/data/sounds/";
```
Comment (Legion2) [inline core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/speech/data/Sounds.java]: this is not needed when the file are relativ the this class

File: core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/speech/data/Sounds.java [hunk 17]
```diff
@@ -56,6 +63,21 @@
...
+	/**
+	 * Get's the sound data of this sound
+	 * 
+	 * @return The {@link AudioInputStream} containing the data.
+	 * @throws IOException
+	 *             When a IO Exception occurs while reading the resource file from disk.
+	 */
+	public AudioInputStream getSoundData() throws IOException {
+		try {
+			return AudioSystem.getAudioInputStream(this.getClass().getClassLoader().getResource(this.path));
```
Comment (Legion2) [inline core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/speech/data/Sounds.java]: get the resource from the class not the ClassLoader

File: core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/speech/output/OutputImpl.java [hunk 18]
```diff
@@ -0,0 +1,104 @@
...
+	private Logger logger;
+	@Reference
+	private TextToSpeech tts;
+	@Reference
+	private AudioManager am;
+
+	private void outputAudioStream(AudioInputStream ais) {
+		List<UUID> registeredAudioEnvs = this.am.getAllRegisteredAudioEnvironments();
+		if (!registeredAudioEnvs.isEmpty()) {
+			this.am.playAudio(registeredAudioEnvs.iterator().next(), ais, AudioManager.OutputBehavior.QUEUE);
```
Comment (Legion2) [inline core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/speech/output/OutputImpl.java]: don't get the first, get one from the identifier

File: core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/speech/data/Sounds.java (hunk 16 above)
Comment (neumantm) [reply core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/speech/data/Sounds.java]: I just took that from the original implementation.

File: api/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/audio/AudioManager.java [hunk 19]
```diff
@@ -72,6 +73,18 @@
 	 */
 	boolean isAudioEnvironmentCurrentlyOutputting(UUID identifier);
 
+	/**
+	 * @return The identifier of the local audio environment.
+	 * @throws NoSuchElementException
+	 *             When this audio manager has no local audio environment.
+	 */
+	UUID getLocalAudioEnvironmentIdentifier() throws NoSuchElementException;
```
Comment (Legion2) [inline api/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/audio/AudioManager.java]: do this in a separate interface

Comment (Legion2) [reply api/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/audio/AudioManager.java]: and add a RunnableService implementation that registers the LocalAudioEnvironment

File: api/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/audio/AudioManager.java [hunk 20]
```diff
@@ -72,6 +73,18 @@
...
+
+	/**
+	 * @return Whether this audio manager has a local audio environment
+	 */
+	boolean hasLocalAudioEnvironment();
```
Comment (Legion2) [inline api/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/audio/AudioManager.java]: this can be removed

File: core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/audio/LocalAudioService.java [hunk 21]
```diff
@@ -0,0 +1,102 @@
...
+				this.identifier = localAe.getAudioEnvironmentIdentifier();
+			} catch (LineUnavailableException e) {
+				this.logger.error("Could not initialize local audio environment.", e);
+			}
+		}
+	}
+
+	private void loadAndCheckProperties() {
+		this.config = this.configurationManager.getConfigurationWithDefaults(CONFIG_NAME);
+		if (this.config == null)
```
Comment (Legion2) [inline core/src/main/java/de/unistuttgart/iaas/amyassist/amy/core/audio/LocalAudioService.java]: this cannot be null
